# Generated by Django 4.2.4 on 2024-04-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_rename_events_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Series',
        ),
    ]
