# Generated by Django 4.2.4 on 2024-04-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_rename_product_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='Image',
            field=models.ImageField(null=True, upload_to='Series'),
        ),
    ]
