# Generated by Django 4.2.4 on 2024-04-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_series_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='Slug',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
