# Generated by Django 4.2.4 on 2024-04-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_series_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='Heading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='Section_Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='Section_Title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='Versions',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='Slug',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
