# Generated by Django 4.2.4 on 2024-04-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_series_heading_series_section_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='Table_Image',
            field=models.ImageField(null=True, upload_to='Series'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Value', models.CharField(max_length=50)),
                ('Series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.series')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.series')),
            ],
        ),
    ]
