# Generated by Django 4.2.4 on 2024-04-11 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_series_table_image_table_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
