# Generated by Django 4.2.4 on 2024-04-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_rename_versions_series_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Specification',
        ),
    ]
