# Generated by Django 4.2.4 on 2024-04-12 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_rename_table_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='Slug',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
