# Generated by Django 4.2.4 on 2024-04-12 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_application_date_application_slug_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='Image',
            field=models.ImageField(null=True, upload_to='Applications'),
        ),
        migrations.AddField(
            model_name='application',
            name='Sub_Title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='Application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.application'),
        ),
        migrations.AlterField(
            model_name='features',
            name='Series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.series'),
        ),
    ]
