# Generated by Django 4.2.4 on 2024-04-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_application_description_application_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to='Works')),
                ('Application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.application')),
            ],
        ),
    ]
