# Generated by Django 4.2.4 on 2024-04-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_works'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='Image',
            field=models.ImageField(null=True, upload_to='Events'),
        ),
        migrations.AddField(
            model_name='event',
            name='Place',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Image',
            field=models.ImageField(null=True, upload_to='Projects'),
        ),
    ]
