# Generated by Django 4.2.4 on 2024-04-12 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_event_date_event_image_event_place_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
