# Generated by Django 4.2.4 on 2024-04-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_project_date_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='Clients')),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
